---
version: 3
options:
  package_manager_path: /usr/bin/microdnf
dependencies:
  galaxy: requirements.yml
  python: requirements.txt
images:
  base_image:
    name: registry.redhat.io/ansible-automation-platform-tech-preview/ee-minimal-rhel9:2.20.5-1777411032
additional_build_steps:
  append_base:
    - RUN $PYCMD -m pip install -U pip
