---
- hosts: all
  connection: local
  gather_facts: false
  vars:
    aap_username: "{{ vault_aap_username | default(lookup('env', 'CONTROLLER_USERNAME')) }}"
    aap_password: "{{ vault_aap_password | default(lookup('env', 'CONTROLLER_PASSWORD')) }}"
    aap_hostname: "{{ vault_aap_hostname | default(lookup('env', 'CONTROLLER_HOST')) }}"
    aap_validate_certs: "{{ vault_aap_validate_certs | default(lookup('env', 'CONTROLLER_VERIFY_SSL')) }}"
  pre_tasks:

    - name: Create a new token using platform username/password
      ansible.platform.token:
        description: 'Creating token to deploy CaC for AAP'
        scope: "write"
        state: present
        aap_hostname: "{{ aap_hostname }}"
        aap_username: "{{ aap_username }}"
        aap_password: "{{ aap_password }}" 
        aap_validate_certs: "{{ aap_validate_certs }}"
      register: aap_token         

  roles:
    - infra.aap_configuration_extended.filetree_read
    - infra.aap_configuration.dispatch

  post_tasks:
    - name: Delete our CaC Token with the token we created
      ansible.platform.token:
        existing_token: "{{ aap_token }}"
        state: absent
      when: aap_token is defined
...
